# Generated by Django 4.1.5 on 2024-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="at_work",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No"),
                    (1, "Yes"),
                    (7, "Redacted"),
                    (8, "Not Aplicable"),
                    (9, "Unknown"),
                ],
                default=9,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="hispanic",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not a Fatality (Not Applicable)"),
                    (1, "Mexican"),
                    (2, "Puerto Rican"),
                    (3, "Cuban"),
                    (4, "Central or South American"),
                    (5, "European Spanish (Since 2000)"),
                    (6, "Hispanic, Origin Not Specified or Other Origin"),
                    (7, "Non-Hispanic"),
                    (97, "Redacted"),
                    (99, "Unknown"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="month_of_death",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                    (88, "Not Applicable (Non-Fatal)"),
                    (97, "Redacted"),
                    (99, "Unknown"),
                ]
            ),
        ),
    ]
