# Generated by Django 4.1.5 on 2024-05-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="county",
        ),
    ]
