# Generated by Django 4.1.5 on 2024-05-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0002_remove_city_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vpic_make",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
