# Generated by Django 4.1.5 on 2024-06-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0004_alter_crashevent_sequence_of_events_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accident",
            old_name="at_intersection",
            new_name="within_interchange_area",
        ),
    ]
