# Generated by Django 4.1.5 on 2024-05-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0005_alter_parkedvehicle_ncsa_make"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="parked_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fatalities.parkedvehicle",
            ),
        ),
    ]
