# Generated by Django 4.1.5 on 2024-05-24 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0007_crashevent_parked_vehicle_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleevent",
            name="parked_vehicle_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parked_vehicle_event_vehicle_1",
                to="fatalities.parkedvehicle",
            ),
        ),
        migrations.AddField(
            model_name="vehicleevent",
            name="parked_vehicle_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parked_vehicle_event_vehicle_2",
                to="fatalities.parkedvehicle",
            ),
        ),
        migrations.AddField(
            model_name="vehiclesequenceofevents",
            name="parked_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fatalities.parkedvehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclesequenceofevents",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fatalities.vehicle",
            ),
        ),
    ]
