# Generated by Django 4.1.5 on 2024-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0007_alter_vehicle_vehicle_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="special_vehicle_use",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Special Use Noted"),
                    (1, "Taxi"),
                    (2, "Vehicle Used as School Transport"),
                    (3, "Vehicle Used as Other Bus"),
                    (4, "Military"),
                    (5, "Police"),
                    (6, "Ambulance (Since 1980)"),
                    (7, "Fire Truck (Since 1982)"),
                    (8, "Non-Transport Emergency Services Vehicle"),
                    (10, "Safety Service Patrols - Incident Response"),
                    (11, "Other Incident Response"),
                    (12, "Towing - Incident Response"),
                    (19, "Motor Vehicle Used for Vehicle Sharing Mobility"),
                    (20, "Motor Vehicle Used for Electronic Ride-Hailing"),
                    (21, "Mail Carrier"),
                    (22, "Public Utility"),
                    (23, "Rental Truck Over 10,000 lbs"),
                    (24, "Truck Operating With Crash Attenuator Equipment"),
                    (98, "Not Reported"),
                    (99, "Reported as Unknown (since 2018)"),
                ],
                default=0,
            ),
        ),
    ]
