# Generated by Django 4.1.5 on 2024-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0008_alter_vehicle_special_vehicle_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="emergency_vehicle_use",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Applicable"),
                    (1, "Yes"),
                    (2, "Non-Emergency, Non-Transport"),
                    (3, "Non-Emergency Transport"),
                    (4, "Emergency Operation, Emergency Warning Equipment Not in Use"),
                    (5, "Emergency Operation, Emergency Warning Equipment in Use"),
                    (
                        6,
                        "Emergency Operation, Emergency Warning Equipment in Use Unknown",
                    ),
                    (8, "Not Reported"),
                    (9, "Reported as Unknown"),
                ],
                default=8,
            ),
        ),
    ]
