# Generated by Django 4.1.5 on 2024-05-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0009_driverrelatedfactor_driver_related_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="damage",
            name="parked_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fatalities.parkedvehicle",
            ),
        ),
        migrations.AlterField(
            model_name="damage",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fatalities.vehicle",
            ),
        ),
    ]
