# Generated by Django 4.1.5 on 2024-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0010_alter_crashevent_area_of_impact_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="cdl_endorsements",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Endorsements Required for This Vehicle"),
                    (1, "Endorsements Required, Complied With"),
                    (2, "Endorsements Required, Not Complied With"),
                    (3, "Endorsements Required, Compliance Unknown"),
                    (7, "No Driver Present/Unknown if Driver Present"),
                    (8, "Not Reported "),
                    (9, "Unknown, if Required"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="cdl_license_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Commercial Driver's License (CDL)"),
                    (1, "Suspended"),
                    (2, "Revoked"),
                    (3, "Expired"),
                    (4, "Cancelled or Denied"),
                    (5, "Disqualified"),
                    (6, "Valid"),
                    (7, "Commercial Learner's Permit (CLP)"),
                    (8, "Other - Not Valid"),
                    (97, "No Driver Present/Unknown if Driver Present"),
                    (98, "Not Reported"),
                    (99, "Unknown License Status"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="compliance_with_license_restrictions",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Restrictions or Not Applicable"),
                    (1, "Restrictions Complied With"),
                    (2, "Restrictions Not Complied With"),
                    (3, "Restrictions, Compliance Unknown"),
                    (7, "No Driver Present/Unknown if Driver Present"),
                    (8, "Not Reported"),
                    (9, "Unknown"),
                ],
                default=9,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_compliance_with_class_of_vehicle",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Licensed"),
                    (1, "No License Required for This Class Vehicle"),
                    (2, "No Valid License for This Class Vehicle"),
                    (3, "Valid License for This Class Vehicle"),
                    (6, "No Driver Present/Unknown if Driver Present"),
                    (7, "Not Reported "),
                    (
                        8,
                        "Unknown if CDL and/or CDL Endorsement Required for This Vehicle",
                    ),
                    (9, "Unknown"),
                ],
                default=9,
            ),
        ),
    ]
