# Generated by Django 4.1.5 on 2024-05-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0010_damage_parked_vehicle_alter_damage_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="damage",
            name="parked_vehicle",
        ),
    ]
