# Generated by Django 4.1.5 on 2024-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0011_alter_vehicle_cdl_endorsements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="speeding_related",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No"),
                    (1, "Yes"),
                    (2, "Yes, Racing"),
                    (3, "Yes, Exceeded Speed Limit"),
                    (4, "Yes, Too Fast for Conditions"),
                    (5, "Yes, Specifics Unknown"),
                    (8, "No Driver Present/Unknown if Driver Present"),
                    (9, "Reported as Unknown"),
                ],
                default=9,
            ),
        ),
    ]
