# Generated by Django 4.1.5 on 2024-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0012_alter_vehicle_speeding_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="airbag_deployed",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nonmotorist"),
                    (1, "Deployed - Front"),
                    (2, "Deployed - Side (Door, Seat Back)"),
                    (3, "Deployed - Curtain (Roof)"),
                    (7, "Deployed - Other (Knee, Air Belt, etc.)"),
                    (8, "Deployed - Combination"),
                    (9, "Deployment - Unknown Location"),
                    (20, "Not Deployed"),
                    (97, "Not a Motor Vehicle Occupant"),
                    (98, "Not Reported"),
                    (99, "Reported as Deployment Unknown"),
                ],
                default=98,
            ),
        ),
    ]
