# Generated by Django 4.1.5 on 2024-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0012_drugs_drug_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="race",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not a Fatality (Not Applicable)"),
                    (1, "White"),
                    (2, "Black or African American"),
                    (3, "North American Indian or Alaska Native"),
                    (4, "Chinese"),
                    (5, "Japanese"),
                    (6, "Native Hawaiian"),
                    (7, "Filipino"),
                    (18, "Asian Indian"),
                    (
                        19,
                        "Other Indian (Includes South and Central America, any others, except North American or Asian Indians)",
                    ),
                    (28, "Korean"),
                    (38, "Samoan"),
                    (48, "Vietnamese"),
                    (58, "Guamanian or Chamorro"),
                    (68, "Other Asian or Pacific Islander"),
                    (78, "Asian or Pacific Islander, No Specific (Individual) Race"),
                    (97, "Multiple Races, Unspecified"),
                    (98, "Other Race"),
                    (99, "Unknown"),
                ],
                default=0,
            ),
        ),
    ]
