# Generated by Django 4.1.5 on 2024-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0014_alter_race_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nonmotorist",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fatalities.person",),
        ),
    ]
