# Generated by Django 4.1.5 on 2024-05-28 17:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0015_nonmotorist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Nonmotorist",
        ),
        migrations.AlterModelManagers(
            name="person",
            managers=[
                ("nonmotorists", django.db.models.manager.Manager()),
            ],
        ),
    ]
