# Generated by Django 4.1.5 on 2024-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0015_alter_driverrelatedfactor_driver_related_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclefactor",
            name="contributing_cause",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (1, "Tires"),
                    (2, "Brake System"),
                    (3, "Steering"),
                    (4, "Suspension"),
                    (5, "Power Train"),
                    (6, "Exhaust System"),
                    (7, "Head Lights"),
                    (8, "Signal Lights"),
                    (9, "Other Lights"),
                    (10, "Wipers"),
                    (11, "Wheels"),
                    (12, "Mirrors"),
                    (13, "Windows/Windshield"),
                    (14, "Body, Doors"),
                    (15, "Truck Coupling/Trailer Hitch/Safety Chains"),
                    (16, "Safety Systems"),
                    (17, "Vehicle Contributing Factors - No Details"),
                    (18, "Horn"),
                    (19, "Driver Seating and Control"),
                    (97, "Other"),
                    (99, "Reported as Unknown"),
                ],
                default=99,
            ),
        ),
    ]
