# Generated by Django 4.1.5 on 2024-05-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0016_delete_nonmotorist_alter_person_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="person",
            managers=[],
        ),
    ]
