# Generated by Django 4.1.5 on 2024-06-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0016_alter_vehiclefactor_contributing_cause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonmotoristprioraction",
            name="nonmotorist_prior_action",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Going to or From School (K-12)"),
                    (2, "Waiting to Cross Roadway"),
                    (3, "Crossing Roadway"),
                    (4, "Jogging/Running"),
                    (
                        5,
                        "Movement Along Roadway With Traffic (in or Adjacent to Travel Lane)",
                    ),
                    (
                        6,
                        "Movement Along Roadway Against Traffic (in or Adjacent to Travel Lane)",
                    ),
                    (7, "Movement on Sidewalk"),
                    (8, "In Roadway-Other (Working, Playing, etc.)"),
                    (
                        9,
                        "Stationary and Adjacent to Roadway (e.g., Shoulder, Median, Sidewalk)",
                    ),
                    (10, "Working in Trafficway (Incident Response)"),
                    (11, "Entering/Exiting a Parked or Stopped Vehicle"),
                    (
                        12,
                        "Disabled Vehicle Related (Working on, Pushing, Leaving/Approaching)",
                    ),
                    (14, "Other"),
                    (15, "None"),
                    (16, "Movement Along Roadway - Direction Unknown (Since 2012)"),
                    (98, "Not Reported"),
                    (99, "Reported as Unknown"),
                ],
                default=98,
            ),
        ),
    ]
