# Generated by Django 4.1.5 on 2024-05-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0019_alter_crashevent_area_of_impact_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accident",
            old_name="exact_location",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="accident",
            name="exact_location_best_guess",
        ),
        migrations.AddField(
            model_name="accident",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accident",
            name="datetime_is_estimated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accident",
            name="location_is_estimated",
            field=models.BooleanField(default=True),
        ),
    ]
