# Generated by Django 5.0.6 on 2024-07-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatalities', '0019_alter_drugs_drug_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fatalities.accident')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
