# Generated by Django 4.1.5 on 2024-05-30 21:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0020_rename_exact_location_accident_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
