# Generated by Django 4.1.5 on 2024-05-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0021_alter_accident_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accident",
            old_name="number_of_vehicles_in_transit",
            new_name="number_of_vehicles_in_transport",
        ),
    ]
