# Generated by Django 4.1.5 on 2024-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fatalities",
            "0022_rename_number_of_vehicles_in_transit_accident_number_of_vehicles_in_transport",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="first_harmful_event",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Rollover/Overturn"),
                    (2, "Fire/Explosion"),
                    (3, "Immersion or Partial Immersion (Since 2012)"),
                    (4, "Gas Inhalation"),
                    (5, "Fell/Jumped From Vehicle"),
                    (6, "Injured in Vehicle (Non-Collision)"),
                    (7, "Other Non-Collision"),
                    (8, "Pedestrian"),
                    (9, "Pedalcyclist"),
                    (10, "Railway Vehicle"),
                    (11, "Live Animal"),
                    (12, "Motor Vehicle In-Transport"),
                    (14, "Parked Motor Vehicle (Not In-Transport)"),
                    (15, "Non-Motorist on Personal Conveyance"),
                    (16, "Thrown or Falling Object"),
                    (17, "Boulder"),
                    (18, "Other Object (Not Fixed)"),
                    (19, "Building"),
                    (20, "Impact Attenuator/Crash Cushion"),
                    (21, "Bridge Pier or Support"),
                    (23, "Bridge Rail (Includes Parapet)"),
                    (24, "Guardrail Face"),
                    (25, "Concrete Traffic Barrier"),
                    (26, "Other Traffic Barrier"),
                    (30, "Utility Pole/Light Support"),
                    (31, "Post, Pole, or Other Supports"),
                    (32, "Culvert"),
                    (33, "Curb"),
                    (34, "Ditch"),
                    (35, "Embankment"),
                    (38, "Fence"),
                    (39, "Wall"),
                    (40, "Fire Hydrant"),
                    (41, "Shrubbery"),
                    (42, "Tree (Standing Only)"),
                    (43, "Other Fixed Object"),
                    (
                        44,
                        "Pavement Surface Irregularity (Ruts, Potholes, Grates, etc.)",
                    ),
                    (45, "Working Motor Vehicle"),
                    (46, "Traffic Signal Support"),
                    (48, "Snow Bank"),
                    (49, "Ridden Animal or Animal-Drawn Conveyance (Since 1998)"),
                    (50, "Bridge Overhead Structure"),
                    (51, "Jackknife (Harmful to This Vehicle)"),
                    (52, "Guardrail End"),
                    (53, "Mail Box"),
                    (
                        54,
                        "Motor Vehicle In-Transport Strikes or Is Struck by Cargo, Persons or Objects Setin-Motion From/by Another Motor Vehicle In-Transport",
                    ),
                    (55, "Motor Vehicle in Motion Outside the Trafficway (Since 2008)"),
                    (57, "Cable Barrier (Since 2008)"),
                    (58, "Ground"),
                    (59, "Traffic Sign Support"),
                    (72, "Cargo/Equipment Loss, Shift, or Damage (Harmful)"),
                    (73, "Object That Had Fallen From Motor Vehicle In-Transport"),
                    (74, "Road Vehicle on Rails"),
                    (91, "Unknown Object Not Fixed"),
                    (93, "Unknown Fixed Object"),
                    (98, "Harmful Event, Details Not Reported (Since 2019)"),
                    (99, "Reported as Unknown"),
                ],
                default=98,
            ),
        ),
    ]
