# Generated by Django 4.1.5 on 2024-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0024_person_parked_vehicle_which_struck_non_motorist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="restraint_system_use",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Used/Not Applicable"),
                    (1, "Shoulder Belt Only Used"),
                    (2, "Lap Belt Only Used"),
                    (3, "Shoulder and Lap Belt Used"),
                    (4, "Child Restraint - Type Unknown"),
                    (8, "Restraint Used - Type Unknown"),
                    (10, "Child Restraint System - Forward Facing (Since 2008)"),
                    (11, "Child Restraint System - Rear Facing (Since 2008)"),
                    (12, "Booster Seat"),
                    (20, "None Used/Not Applicable"),
                    (96, "Not a Motor Vehicle Occupant"),
                    (97, "Other"),
                    (98, "Not Reported"),
                    (99, "Unknown/Reported as Unknown (Since 2018)"),
                ],
                default=98,
            ),
        ),
    ]
