# Generated by Django 4.1.5 on 2024-07-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0025_alter_person_restraint_system_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverrelatedfactor",
            name="driver_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (1, "Drowsy, Sleepy, Asleep, Fatigued"),
                    (2, "Ill, Passed out/Blackout"),
                    (3, "Emotional (e.g., Depression, Angry, Disturbed)"),
                    (4, "Reaction to or Failure to Take Drugs/Medication"),
                    (
                        5,
                        "Under the Influence of Alcohol, Drugs, or Medication (2003-2009)",
                    ),
                    (
                        6,
                        "Careless Driving, Inattentive Operation, Improper Driving, Driving Without Due Care",
                    ),
                    (7, "Restricted to Wheelchair"),
                    (8, "Road Rage/Aggressive Driving"),
                    (10, "Looked but Did Not See"),
                    (12, "Mother of Dead Fetus/Mother of Infant Born Post Crash"),
                    (
                        13,
                        "Person with an Intellectual, Cognitive, or Developmental Disability",
                    ),
                    (14, "Failure to Take Drugs/Medication (1995-2004)"),
                    (15, "Seat Back Not in Normal Position, Seat Back Reclined"),
                    (16, "Police or Law Enforcement Officer"),
                    (17, "Running off Road (2000-2003)"),
                    (18, "Traveling on Prohibited Trafficways"),
                    (19, "Legally Driving on Suspended or Revoked License"),
                    (
                        20,
                        "Leaving Vehicle Unattended With Engine Running; Leaving Vehicle Unattended in Roadway",
                    ),
                    (
                        21,
                        "Overloading or Improper Loading of Vehicle With Passenger or Cargo",
                    ),
                    (22, "Towing or Pushing Vehicle Improperly"),
                    (23, "Failing to Dim Lights or to Have Lights on When Required"),
                    (24, "Operating Without Required Equipment"),
                    (26, "Following Improperly"),
                    (27, "Improper or Erratic Lane Changing"),
                    (28, "Improper Lane Usage"),
                    (29, "Intentional Illegal Driving off the Roadway"),
                    (30, "Making Improper Entry to or Exit From Trafficway"),
                    (31, "Starting or Backing Improperly"),
                    (
                        32,
                        "Opening Vehicle Closure Into Moving Traffic or Vehicle Is in Motion",
                    ),
                    (
                        33,
                        "Passing Where Prohibited by Posted Signs, Pavement Markings, or School Bus Displaying Warning Not to Pass",
                    ),
                    (34, "Improper Passing Location"),
                    (
                        35,
                        "Passing With Insufficient Distance or Inadequate Visibility or Failing to Yield to Overtaking Vehicle",
                    ),
                    (
                        36,
                        "Operating the Vehicle in an Erratic, Reckless, Careless or Negligent Manner",
                    ),
                    (
                        37,
                        "Police Pursuing This Driver or Police Officer in Pursuit (See Police Pursuits in Appendix C: Additional Data Element Information)",
                    ),
                    (38, "Failure to Yield Right-of-Way"),
                    (
                        39,
                        "Failure to Obey Actual Traffic Signs, Traffic Control Devices or Traffic Officers, Failure to Observe Safety Zone Traffic Laws",
                    ),
                    (40, "Passing Through or Around Barrier"),
                    (
                        41,
                        "Failure to Observe Warnings or Instructions on Vehicle Displaying Them",
                    ),
                    (42, "Failure to Signal Intentions"),
                    (
                        44,
                        "Driving too Fast for Conditions or in Excess of Posted Speed Limit (1982-2008)",
                    ),
                    (45, "Driving Less Than Posted Maximum"),
                    (46, "Racing"),
                    (
                        47,
                        "Making Right Turn From Left-Turn Lane or Making Left Turn From Right-Turn Lane",
                    ),
                    (48, "Making Improper Turn"),
                    (
                        49,
                        "Failure to Comply With Physical Restrictions of License (1982-2004)",
                    ),
                    (50, "Driving Wrong Way on One-Way Trafficway"),
                    (
                        51,
                        "Driving on Wrong Side of Two-way Trafficway (Intentionally or Unintentionally)",
                    ),
                    (52, "Operator Inexperience"),
                    (53, "Unfamiliar With Roadway"),
                    (54, "Stopping in Roadway (Vehicle Not Abandoned)"),
                    (55, "Improper Management of Vehicle Controls"),
                    (56, "Object Interference With Vehicle Controls"),
                    (57, "Driving With Tire-Related Problems"),
                    (58, "Over Correcting"),
                    (59, "Getting off/out of a Vehicle"),
                    (60, "Alcohol and/or Drug Test Refused"),
                    (61, "Rain, Snow, Fog, Smoke, Sand, Dust (1982-2008)"),
                    (62, "Reflected Glare, Bright Sunlight, Headlights (1982-2008)"),
                    (
                        63,
                        "Curve, Hill, or Other Design Features (Including Traffic Signs, Embankment 1982-2008)",
                    ),
                    (64, "Building, Billboard, etc. (1982-2008)"),
                    (65, "Trees, Crops, Vegetation (1982-2008)"),
                    (66, "Motor Vehicle (Including Load 1982-2008)"),
                    (67, "Parked Vehicle (1982-2008)"),
                    (68, "Splash or Spray of Passing Vehicle (1982-2008)"),
                    (69, "Inadequate Defrost or Defog System (1982-2008)"),
                    (70, "Inadequate Vehicle Lighting System (1982-2008)"),
                    (71, "Obstructing Angles on Vehicle (1982-2008)"),
                    (72, "Mirrors - Rear View (1982-2008)"),
                    (
                        73,
                        "Driver Has Not Complied With Learners Permit or Intermediate Driver License Restrictions (GDL Restrictions)",
                    ),
                    (
                        74,
                        "Driver Has Not Complied With Physical or Other Imposed Restrictions",
                    ),
                    (75, "Broken or Improperly Cleaned Windshield (1982-2008)"),
                    (76, "Other Obstruction (1982-2008)"),
                    (77, "Severe Crosswind"),
                    (78, "Wind From Passing Truck"),
                    (79, "Slippery or Loose Surface"),
                    (80, "Tire Blow-Out or Flat"),
                    (81, "Debris or Objects in Road"),
                    (82, "Ruts, Holes, Bumps in Road"),
                    (83, "Live Animals in Road"),
                    (84, "Vehicle in Road"),
                    (85, "Phantom Vehicle"),
                    (86, "Pedestrian, Pedalcyclist, or Other Non-Motorist in Road"),
                    (
                        87,
                        "Ice, Water, Snow, Slush, Sand, Dirt, Oil, Wet Leaves on Road",
                    ),
                    (88, "Trailer Fishtailing or Swaying"),
                    (
                        89,
                        "Driver has a Driving Record or Driver’s License From More Than One State",
                    ),
                    (90, "Hit-and-Run Vehicle Driver"),
                    (
                        91,
                        "Non-Traffic Violation Charged (Manslaughter, Homicide, or Other Assault Offense Committed Without Malice, Since 1986)",
                    ),
                    (92, "Other Non-Moving Traffic Violation (1986-2011)"),
                    (93, "Cellular Telephone / Other Electronic Device"),
                    (94, "Emergency Medical Service Personnel"),
                    (95, "Fire Personnel"),
                    (96, "Tow Operator"),
                    (
                        97,
                        "Transportation (i.e., Maintenance Workers, Safety Service Patrol Operators, etc.)",
                    ),
                    (99, "Reported as Unknown"),
                    (101, "Carrying Hazardous Cargo Improperly (1994-2009)"),
                ],
                default=0,
            ),
        ),
    ]
