# Generated by Django 4.1.5 on 2024-07-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0027_fatalitytotals"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatalitytotals",
            name="bike_fatalities",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fatalitytotals",
            name="ped_fatalities",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
