# Generated by Django 4.2.16 on 2025-01-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0029_podcastepisode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedditPost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.CharField(max_length=16)),
                ("title", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("score", models.BigIntegerField()),
                ("url", models.TextField(blank=True, null=True)),
                ("created_utc", models.PositiveBigIntegerField()),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fatalities.subreddit",
                    ),
                ),
            ],
            options={
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["subreddit", "slug"],
                        name="fatalities__subredd_a24bf5_idx",
                    ),
                    models.Index(
                        fields=["created_utc"], name="fatalities__created_a80a47_idx"
                    ),
                ],
                "unique_together": {("subreddit", "slug")},
            },
        ),
    ]
