# Generated by Django 4.2.16 on 2025-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0030_subreddit_redditpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiReddit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.TextField()),
            ],
            options={
                "db_table": "multireddit",
            },
        ),
    ]
