# Generated by Django 4.2.16 on 2025-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0031_multireddit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
