# Generated by Django 4.2.16 on 2025-02-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0032_alter_redditpost_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "customer_email",
                "managed": True,
            },
        ),
    ]
