# Generated by Django 4.2.16 on 2025-05-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0034_missedconnection_missedconnectioncomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugs",
            name="actual_drug_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drugs",
            name="drug_quantity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Test Not Given"),
                    (1, "None Detected/Below Threshold"),
                    (2, "Actual Drug Quantity"),
                    (3, "Presumptive Positive"),
                    (4, "Drugs Detected, Unknown Testing Method"),
                    (96, "Not Reported"),
                    (97, "Tested for Drugs, Results Unknown"),
                    (98, "Tested for Drugs, Drugs Detected, Unknown Quantity"),
                    (99, "Reported as Unknown if Tested for Drugs"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="drugs",
            name="drug_test_method",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Test Not Given"),
                    (1, "Enzyme-Linked Immunosorbent Assay [ELISA]"),
                    (2, "Enzyme-Multiplied Immunoassay Technique [EMIT]"),
                    (3, "Liquid Chromatography/Tandem Mass Spectrometry [LC/MS-MS]"),
                    (4, "Headspace Gas Chromatography [HS/GC]"),
                    (
                        5,
                        "Liquid Chromatography/Time of Flight—Mass Spectrometry [LC/TOF-MS]",
                    ),
                    (6, "Enzyme Immunoassay [EIA]"),
                    (8, "Other Screening Test Method [Specify:]"),
                    (9, "Unknown Screening Test Method"),
                    (11, "High-Performance Liquid Chromatography [HPLC]"),
                    (12, "Liquid Chromatography/Mass Spectrometry [LC/MS]"),
                    (
                        13,
                        "Liquid Chromatography/Time of Flight—Mass Spectrometry [LC/TOF - MS]",
                    ),
                    (14, "Gas Chromatography and Mass Spectrometry [GC/MS]"),
                    (15, "Gas Chromatography [GC]"),
                    (16, "Liquid Chromatography/Tandem Mass Spectrometry [LC/MS-MS]"),
                    (
                        17,
                        "Liquid Chromatography/Time of Flight—Tandem Mass Spectrometry [LC/TOF-MS/MS]",
                    ),
                    (20, "Quadrupole Time of Flight [QTOF]"),
                    (21, "Liquid Chromatography/Quadrupole Time of Flight [LC/QTOF]"),
                    (22, "Quadrupole Time of Flight Mass Spectrometry [QTOF MS]"),
                    (23, "Gas Chromatography and Tandem Mass Spectrometry [GC/MS-MS]"),
                    (24, "Headspace Gas Chromatography [HS-GC]"),
                    (25, "Gas Chromatography With Flame Ionization Detection [GC FID]"),
                    (
                        26,
                        "Headspace Gas Chromatography With Flame Ionization Detection [HS-GC FID]",
                    ),
                    (18, "Other Confirmatory Test Method [Specify:]"),
                    (19, "Unknown Confirmatory Test Method"),
                    (96, "Not Reported"),
                    (97, "Unknown Testing Method"),
                    (99, "Reported as Unknown if Tested"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="drugs",
            name="unit_of_measure",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "mg/dL"),
                    (2, "mg/L"),
                    (3, "mcg/L"),
                    (4, "gm%"),
                    (5, "ng/mL"),
                    (6, "mcg/L"),
                    (7, "%"),
                    (8, "Other [Specify:]"),
                    (-9, "Not Applicable"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="functional_system",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Interstate"),
                    (2, "Other Freeways and Expressways"),
                    (3, "Other Principal Arterial"),
                    (4, "Minor Arterial"),
                    (5, "Major Collector"),
                    (6, "Minor Collector"),
                    (7, "Local"),
                    (96, "Trafficway Not In State Inventory"),
                    (98, "Not Reported"),
                    (99, "Unknown"),
                ],
                default=9,
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="road_owner",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "State Highway Agency"),
                    (2, "County Highway Agency"),
                    (3, "Town or Township Highway Agency"),
                    (4, "City or Municipal Highway Agency"),
                    (11, "State Park, Forest or Reservation Agency"),
                    (12, "Local Park, Forest or Reservation Agency"),
                    (21, "Other State Agency"),
                    (25, "Other Local Agency"),
                    (26, "Private (Other Than Railroad)"),
                    (27, "Railroad"),
                    (31, "State Toll Road"),
                    (32, "Local Toll Authority"),
                    (40, "Other Public Instrumentality (i.e., Airport)"),
                    (50, "Indian Tribe Nation"),
                    (60, "Other Federal Agency"),
                    (62, "Bureau of Indian Affairs"),
                    (63, "Bureau of Fish and Wildlife"),
                    (64, "U.S. Forest Service"),
                    (66, "National Park Service"),
                    (67, "Tennessee Valley Authority"),
                    (68, "Bureau of Land Management"),
                    (69, "Bureau of Reclamation"),
                    (70, "Corps of Engineers"),
                    (72, "Air Force"),
                    (74, "Navy/Marines"),
                    (80, "Army"),
                    (95, "Other"),
                    (96, "Trafficway Not in State Inventory"),
                    (98, "Not Reported"),
                    (99, "Unknown"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="route_signing",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Signed"),
                    (1, "Interstate"),
                    (2, "U.S. Highway"),
                    (3, "State Highway"),
                    (4, "County"),
                    (5, "Township"),
                    (6, "Municipal"),
                    (7, "Local Street - Frontage Road"),
                    (8, "Other"),
                    (10, "Parkway Marker or Forest Route Marker"),
                    (11, "Off-Interstate Business Marker"),
                    (12, "Secondary Route"),
                    (13, "Bureau of Indian Affairs"),
                    (95, "Other"),
                    (96, "Trafficway Not in State Inventory"),
                    (99, "Unknown/Not Reported"),
                ],
                default=9,
            ),
        ),
        migrations.AlterField(
            model_name="crashrelatedfactors",
            name="crash_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (
                        1,
                        "Inadequate Warning of Exits, Lanes Narrowing, Traffic Controls, etc.",
                    ),
                    (2, "Shoulder Design or Condition"),
                    (3, "Other Maintenance or Construction-Created Condition"),
                    (4, "No or Obscured Pavement Marking"),
                    (5, "Surface Under Water"),
                    (
                        6,
                        "Inadequate Construction or Poor Design of Roadway, Bridge, etc.",
                    ),
                    (7, "Surface Washed out (Caved in, Road Slippage)"),
                    (10, "Emergency Vehicle Related"),
                    (12, "Distracted Driver of a Non-Contact Vehicle"),
                    (13, "Aggressive Driving/Road Rage by Non-Contact Vehicle Driver"),
                    (
                        14,
                        "Motor Vehicle Struck by Falling Cargo or Something That Came Loose From or Something That Was Set in Motion by a Vehicle",
                    ),
                    (
                        15,
                        "Non-Occupant Struck by Falling Cargo, or Something Came Loose From or Something That Was Set in Motion by a Vehicle",
                    ),
                    (16, "Non-Occupant Struck Vehicle"),
                    (17, "Stopped Vehicle Set in Motion by Non-Driver"),
                    (
                        18,
                        "Date of Crash and Date of EMS Notification Were Not Same Day",
                    ),
                    (19, "Recent Previous Crash Scene Nearby"),
                    (20, "Police-Pursuit-Involved"),
                    (21, "Within Designated School Zone"),
                    (
                        22,
                        "Speed Limit Is a Statutory Limit as Recorded or Was Determined as This State’s “Basic Rule”",
                    ),
                    (23, "Indication of a Stalled/Disabled Vehicle"),
                    (
                        24,
                        "Unstabilized Situation Began and All Harmful Events Occurred off of the Roadway",
                    ),
                    (25, "Toll Booth/Plaza Related"),
                    (26, "Prior Non-Recurring Incident"),
                    (27, "Backup Due to Prior Crash"),
                    (28, "Regular Congestion"),
                    (30, "Obstructed Crosswalks"),
                    (31, "Related to a Bus Stop"),
                    (42, "Uncontrolled Intersection or Railroad Crossing"),
                    (102, "Aggressive Driving by Non-Contact Vehicle Driver"),
                    (103, "Road Rage by Non-Contact Vehicle Driver"),
                    (999, "Unknown"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="driverrelatedfactor",
            name="driver_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (1, "Drowsy, Sleepy, Asleep, Fatigued"),
                    (2, "Ill, Passed out/Blackout"),
                    (3, "Emotional (e.g., Depression, Angry, Disturbed)"),
                    (4, "Reaction to or Failure to Take Drugs/Medication"),
                    (
                        5,
                        "Under the Influence of Alcohol, Drugs, or Medication (2003-2009)",
                    ),
                    (
                        6,
                        "Careless Driving, Inattentive Operation, Improper Driving, Driving Without Due Care",
                    ),
                    (7, "Restricted to Wheelchair"),
                    (8, "Road Rage/Aggressive Driving"),
                    (10, "Looked but Did Not See"),
                    (12, "Mother of Dead Fetus/Mother of Infant Born Post Crash"),
                    (
                        13,
                        "Person with an Intellectual, Cognitive, or Developmental Disability",
                    ),
                    (14, "Failure to Take Drugs/Medication (1995-2004)"),
                    (15, "Seat Back Not in Normal Position, Seat Back Reclined"),
                    (16, "Police or Law Enforcement Officer"),
                    (17, "Running off Road (2000-2003)"),
                    (18, "Traveling on Prohibited Trafficways"),
                    (19, "Legally Driving on Suspended or Revoked License"),
                    (
                        20,
                        "Leaving Vehicle Unattended With Engine Running; Leaving Vehicle Unattended in Roadway",
                    ),
                    (
                        21,
                        "Overloading or Improper Loading of Vehicle With Passenger or Cargo",
                    ),
                    (22, "Towing or Pushing Vehicle Improperly"),
                    (23, "Failing to Dim Lights or to Have Lights on When Required"),
                    (24, "Operating Without Required Equipment"),
                    (26, "Following Improperly"),
                    (27, "Improper or Erratic Lane Changing"),
                    (28, "Improper Lane Usage"),
                    (29, "Intentional Illegal Driving off the Roadway"),
                    (30, "Making Improper Entry to or Exit From Trafficway"),
                    (31, "Starting or Backing Improperly"),
                    (
                        32,
                        "Opening Vehicle Closure Into Moving Traffic or Vehicle Is in Motion",
                    ),
                    (
                        33,
                        "Passing Where Prohibited by Posted Signs, Pavement Markings, or School Bus Displaying Warning Not to Pass",
                    ),
                    (34, "Improper Passing Location"),
                    (
                        35,
                        "Passing With Insufficient Distance or Inadequate Visibility or Failing to Yield to Overtaking Vehicle",
                    ),
                    (
                        36,
                        "Operating the Vehicle in an Erratic, Reckless, Careless or Negligent Manner",
                    ),
                    (
                        37,
                        "Police Pursuing This Driver or Police Officer in Pursuit (See Police Pursuits in Appendix C: Additional Data Element Information)",
                    ),
                    (38, "Failure to Yield Right-of-Way"),
                    (
                        39,
                        "Failure to Obey Actual Traffic Signs, Traffic Control Devices or Traffic Officers, Failure to Observe Safety Zone Traffic Laws",
                    ),
                    (40, "Passing Through or Around Barrier"),
                    (
                        41,
                        "Failure to Observe Warnings or Instructions on Vehicle Displaying Them",
                    ),
                    (42, "Failure to Signal Intentions"),
                    (
                        44,
                        "Driving too Fast for Conditions or in Excess of Posted Speed Limit (1982-2008)",
                    ),
                    (45, "Driving Less Than Posted Maximum"),
                    (46, "Racing"),
                    (
                        47,
                        "Making Right Turn From Left-Turn Lane or Making Left Turn From Right-Turn Lane",
                    ),
                    (48, "Making Improper Turn"),
                    (
                        49,
                        "Failure to Comply With Physical Restrictions of License (1982-2004)",
                    ),
                    (50, "Driving Wrong Way on One-Way Trafficway"),
                    (
                        51,
                        "Driving on Wrong Side of Two-way Trafficway (Intentionally or Unintentionally)",
                    ),
                    (52, "Operator Inexperience"),
                    (53, "Unfamiliar With Roadway"),
                    (54, "Stopping in Roadway (Vehicle Not Abandoned)"),
                    (55, "Improper Management of Vehicle Controls"),
                    (56, "Object Interference With Vehicle Controls"),
                    (57, "Driving With Tire-Related Problems"),
                    (58, "Over Correcting"),
                    (59, "Getting off/out of a Vehicle"),
                    (60, "Alcohol and/or Drug Test Refused"),
                    (61, "Rain, Snow, Fog, Smoke, Sand, Dust (1982-2008)"),
                    (62, "Reflected Glare, Bright Sunlight, Headlights (1982-2008)"),
                    (
                        63,
                        "Curve, Hill, or Other Design Features (Including Traffic Signs, Embankment 1982-2008)",
                    ),
                    (64, "Building, Billboard, etc. (1982-2008)"),
                    (65, "Trees, Crops, Vegetation (1982-2008)"),
                    (66, "Motor Vehicle (Including Load 1982-2008)"),
                    (67, "Parked Vehicle (1982-2008)"),
                    (68, "Splash or Spray of Passing Vehicle (1982-2008)"),
                    (69, "Inadequate Defrost or Defog System (1982-2008)"),
                    (70, "Inadequate Vehicle Lighting System (1982-2008)"),
                    (71, "Obstructing Angles on Vehicle (1982-2008)"),
                    (72, "Mirrors - Rear View (1982-2008)"),
                    (
                        73,
                        "Driver Has Not Complied With Learners Permit or Intermediate Driver License Restrictions (GDL Restrictions)",
                    ),
                    (
                        74,
                        "Driver Has Not Complied With Physical or Other Imposed Restrictions",
                    ),
                    (75, "Broken or Improperly Cleaned Windshield (1982-2008)"),
                    (76, "Other Obstruction (1982-2008)"),
                    (77, "Severe Crosswind"),
                    (78, "Wind From Passing Truck"),
                    (79, "Slippery or Loose Surface"),
                    (80, "Tire Blow-Out or Flat"),
                    (81, "Debris or Objects in Road"),
                    (82, "Ruts, Holes, Bumps in Road"),
                    (83, "Live Animals in Road"),
                    (84, "Vehicle in Road"),
                    (85, "Phantom Vehicle"),
                    (86, "Pedestrian, Pedalcyclist, or Other Non-Motorist in Road"),
                    (
                        87,
                        "Ice, Water, Snow, Slush, Sand, Dirt, Oil, Wet Leaves on Road",
                    ),
                    (88, "Trailer Fishtailing or Swaying"),
                    (
                        89,
                        "Driver has a Driving Record or Driver’s License From More Than One State",
                    ),
                    (90, "Hit-and-Run Vehicle Driver"),
                    (
                        91,
                        "Non-Traffic Violation Charged (Manslaughter, Homicide, or Other Assault Offense Committed Without Malice, Since 1986)",
                    ),
                    (92, "Other Non-Moving Traffic Violation (1986-2011)"),
                    (93, "Cellular Telephone / Other Electronic Device"),
                    (94, "Emergency Medical Service Personnel"),
                    (95, "Fire Personnel"),
                    (96, "Tow Operator"),
                    (
                        97,
                        "Transportation (i.e., Maintenance Workers, Safety Service Patrol Operators, etc.)",
                    ),
                    (99, "Reported as Unknown"),
                    (100, "Using a Belt-Positioning Device or Other"),
                    (101, "Carrying Hazardous Cargo Improperly (1994-2009)"),
                    (102, "Aggressive Driving"),
                    (103, "Road Rage"),
                    (104, "Police Pursuing This Driver"),
                    (105, "Police Officer in Pursuit"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="crash_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Impact"),
                    (
                        1,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Drive off Road",
                    ),
                    (
                        2,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Control/Traction Loss",
                    ),
                    (
                        3,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Avoid Collision With Vehicle, Pedestrian, Animal",
                    ),
                    (
                        4,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Specifics Other",
                    ),
                    (
                        5,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Specifics Unknown",
                    ),
                    (
                        6,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Drive off Road",
                    ),
                    (
                        7,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Control/Traction Loss",
                    ),
                    (
                        8,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Avoid Collision With Vehicle, Pedestrian, Animal",
                    ),
                    (
                        9,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Specifics Other",
                    ),
                    (
                        10,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Specifics Unknown",
                    ),
                    (
                        11,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Parked Vehicle",
                    ),
                    (
                        12,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Stationary Object",
                    ),
                    (
                        13,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Pedestrian/Animal",
                    ),
                    (
                        14,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - End Departure",
                    ),
                    (
                        15,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        16,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        20,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped",
                    ),
                    (
                        21,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Straight",
                    ),
                    (
                        22,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Left",
                    ),
                    (
                        23,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Right",
                    ),
                    (
                        24,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower",
                    ),
                    (
                        25,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Straight",
                    ),
                    (
                        26,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Left",
                    ),
                    (
                        27,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Right",
                    ),
                    (
                        28,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing)",
                    ),
                    (
                        29,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Straight",
                    ),
                    (
                        30,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Left",
                    ),
                    (
                        31,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Right",
                    ),
                    (
                        32,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Specifics Other",
                    ),
                    (
                        33,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Specifics Unknown",
                    ),
                    (
                        34,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        35,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        36,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        37,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        38,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        39,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        40,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        41,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        42,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        43,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        44,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Straight Ahead on Left",
                    ),
                    (
                        45,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Straight Ahead on Left/Right",
                    ),
                    (
                        46,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Changing Lanes to the Right",
                    ),
                    (
                        47,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Changing Lanes to the Left",
                    ),
                    (
                        48,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Specifics Other",
                    ),
                    (
                        49,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Specifics Unknown",
                    ),
                    (
                        52,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION G: HEAD-ON - Specifics Other",
                    ),
                    (
                        53,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION G: HEAD-ON - Specifics Unknown",
                    ),
                    (
                        54,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        55,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        56,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        57,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        58,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        59,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        60,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        61,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        62,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        63,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        64,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Lateral Move (Left/Right)",
                    ),
                    (
                        65,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Lateral Move (Going Straight)",
                    ),
                    (
                        66,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Specifics Other",
                    ),
                    (
                        67,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Specifics Unknown",
                    ),
                    (
                        74,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION J: TURN ACROSS PATH - Specifics Other",
                    ),
                    (
                        75,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION J: TURN ACROSS PATH - Specifics Unknown",
                    ),
                    (
                        84,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION K: TURN INTO PATH - Specifics Other",
                    ),
                    (
                        85,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION K: TURN INTO PATH - Specifics Unknown",
                    ),
                    (
                        90,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - CONFIGURATION L: STRAIGHT PATHS - Specifics Other",
                    ),
                    (
                        91,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - CONFIGURATION L: STRAIGHT PATHS - Specifics Unknown",
                    ),
                    (101, "CATEGORY I: SINGLE DRIVER - Right Roadside Departure"),
                    (102, "CATEGORY I: SINGLE DRIVER - Left Roadside Departure"),
                    (
                        103,
                        "CATEGORY I: SINGLE DRIVER - Struck Object While Moving Forward",
                    ),
                    (
                        201,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Leading Vehicle",
                    ),
                    (
                        202,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Trailing Vehicle",
                    ),
                    (
                        203,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Other or Unknown",
                    ),
                    (
                        204,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Frontal Impact After Maneuver",
                    ),
                    (
                        205,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Rear End Impact After Maneuver",
                    ),
                    (
                        206,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Other or Unknown",
                    ),
                    (
                        207,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Sideswipe Angle, Vehicle on Left",
                    ),
                    (
                        208,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Sideswipe Angle, Vehicle on Right",
                    ),
                    (
                        209,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - (Sideswipe Angle, Other or Unknown",
                    ),
                    (
                        301,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move [Left/Right], Head-On, Sideswipe, or Angle",
                    ),
                    (
                        302,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move [Going Straight], Head-On, Sideswipe, or Angle",
                    ),
                    (
                        303,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move, Other or Unknown",
                    ),
                    (
                        304,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Departed Lane",
                    ),
                    (
                        305,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Remained in Lane",
                    ),
                    (
                        306,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Other or Unknown",
                    ),
                    (
                        401,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Opposite Directions [Left/Right]",
                    ),
                    (
                        402,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Opposite Directions [Going Straight]",
                    ),
                    (
                        403,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Turning Right]",
                    ),
                    (
                        404,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Going Straight]",
                    ),
                    (
                        405,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Turning Left]",
                    ),
                    (
                        406,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Going Straight]",
                    ),
                    (
                        407,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Other or Unknown",
                    ),
                    (
                        408,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Turning Left]",
                    ),
                    (
                        409,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Going Straight]",
                    ),
                    (
                        410,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Turning Right]",
                    ),
                    (
                        411,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Going Straight]",
                    ),
                    (
                        412,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Turning Right]",
                    ),
                    (
                        413,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Going Straight]",
                    ),
                    (
                        414,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Turning Left]",
                    ),
                    (
                        415,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Going Straight]",
                    ),
                    (
                        416,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Other or Unknown",
                    ),
                    (
                        501,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Striking from the Right",
                    ),
                    (
                        502,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Struck on the Right",
                    ),
                    (
                        503,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Striking from the Left",
                    ),
                    (
                        504,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Struck on the Left",
                    ),
                    (
                        505,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Other or Unknown",
                    ),
                    (992, "CATEGORY VI: MISCELLANEOUS - Backing Vehicle"),
                    (993, "CATEGORY VI: MISCELLANEOUS - Other Vehicle"),
                    (998, "CATEGORY VI: MISCELLANEOUS - Other Crash Type"),
                    (999, "CATEGORY VI: MISCELLANEOUS - Unknown Crash Type"),
                ],
                default=99,
            ),
        ),
    ]
