# Generated by Django 4.2.16 on 2025-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fatalities",
            "0036_alter_nonmotoristprioraction_nonmotorist_prior_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclefactor",
            name="contributing_cause",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (1, "Tires"),
                    (2, "Brake System"),
                    (3, "Steering"),
                    (4, "Suspension"),
                    (5, "Power Train"),
                    (6, "Exhaust System"),
                    (7, "Head Lights"),
                    (8, "Signal Lights"),
                    (9, "Other Lights"),
                    (10, "Wipers"),
                    (11, "Wheels"),
                    (12, "Mirrors"),
                    (13, "Windows/Windshield"),
                    (14, "Body, Doors"),
                    (15, "Truck Coupling/Trailer Hitch/Safety Chains"),
                    (16, "Safety Systems"),
                    (17, "Vehicle Contributing Factors - No Details"),
                    (18, "Horn"),
                    (19, "Driver Seating and Control"),
                    (97, "Other"),
                    (98, "Not Reported"),
                    (99, "Reported as Unknown"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclerelatedfactor",
            name="vehicle_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (29, "Default Code Used for Vehicle Numbering"),
                    (30, "Multi-Wheeled Motorcycle Conversion"),
                    (31, "Hit-and-Run Vehicle (1982-2008)"),
                    (32, "Vehicle Registration for a Person with a Disability"),
                    (33, "Vehicle Being Pushed by Non-Motorist"),
                    (
                        34,
                        "Vehicle Impact Point-the Result of Something Set in Motion (1998-2003)",
                    ),
                    (35, "Reconstructed/Altered Vehicle"),
                    (36, "Electric/Alternative Fuel Vehicle (Since 1999)"),
                    (37, "Transporting Children to/From Head Start/Day Care"),
                    (38, "Vehicle Went Airborne During Crash (2001-2003)"),
                    (
                        39,
                        "Highway Construction, Maintenance or Utility Vehicle, In-Transport (Inside or Outside Work Zone)",
                    ),
                    (40, "Highway Incident Response Vehicle(Since 2002)"),
                    (
                        41,
                        "Police Fire or EMS Vehicle Working at the Scene of an Emergency or Performing Other Traffic Control Activities",
                    ),
                    (
                        42,
                        "Other Working Vehicle (Not Construction, Maintenance, Utility, Police, Fire, or EMS Vehicle)",
                    ),
                    (
                        43,
                        "Hazardous Materials/Cargo Released From This Vehicle (2005-2006)",
                    ),
                    (44, "Adaptive Equipment"),
                    (45, "Slide-in Camper"),
                ],
                default=0,
            ),
        ),
    ]
