# Generated by Django 4.2.16 on 2025-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0037_alter_vehiclefactor_contributing_cause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverdistracted",
            name="distracted_by",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Distracted"),
                    (1, "Looked but Did Not See"),
                    (3, "By Other Occupant(s)"),
                    (4, "By a Moving Object in Vehicle"),
                    (5, "While Talking or Listening to Mobile Phone"),
                    (6, "While Manipulating Mobile Phone"),
                    (7, "While Adjusting Audio or Climate Controls"),
                    (9, "While Using Other Component/Controls Integral to Vehicle"),
                    (
                        10,
                        "While Using or Reaching for Device/Object Brought Into Vehicle",
                    ),
                    (12, "Distracted by Outside Person, Object or Event"),
                    (13, "Eating or Drinking"),
                    (14, "Smoking Related"),
                    (15, "Other Mobile Phone Related"),
                    (16, "No Driver Present/Unknown if Driver Present"),
                    (17, "Distraction/Inattention"),
                    (18, "Distraction/Careless"),
                    (19, "Careless/Inattentive"),
                    (92, "Distraction (Distracted), Details Unknown"),
                    (93, "Inattention (Inattentive), Details Unknown"),
                    (96, "Not Reported"),
                    (97, "Lost in Thought/Daydreaming"),
                    (98, "Other Distraction"),
                    (99, "Reported as Unknown if Distracted"),
                ],
                default=99,
            ),
        ),
    ]
