# Generated by Django 4.2.16 on 2025-06-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0040_alter_driverrelatedfactor_driver_related_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonmotoristcontributingcircumstance",
            name="nonmotorist_contributing_circumstance",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (1, "Dart-out - Visual Obstruction Noted"),
                    (2, "Failure to Yield Right-Of-Way"),
                    (3, "Failure to Obey Traffic Signs, Signals or Officer"),
                    (4, "In Roadway Improperly (Standing, Lying, Working, Playing)"),
                    (5, "Entering/Exiting Parked or Stopped Vehicle"),
                    (6, "Inattentive (Talking, Eating, etc.)"),
                    (7, "Improper Turn/Merge"),
                    (8, "Improper Passing"),
                    (9, "Wrong-Way Riding or Walking"),
                    (10, "Riding on Wrong Side of Road"),
                    (11, "Dash - Run, No Visual Obstruction Noted"),
                    (12, "Improper Crossing of Roadway or Intersection (Jaywalking)"),
                    (13, "Failing to Have Lights on When Required"),
                    (14, "Operating Without Required Equipment"),
                    (15, "Improper or Erratic Lane Changing"),
                    (16, "Failure to Keep in Proper Lane or Running off Road"),
                    (17, "Making Improper Entry to or Exit From Trafficway"),
                    (
                        18,
                        "Operating in Other Erratic, Reckless, Careless or Negligent Manner",
                    ),
                    (19, "Not Visible (Dark Clothing, No Lighting, etc.)"),
                    (
                        20,
                        "Passing With Insufficient Distance or Inadequate Visibility or Failing to Yield to Overtaking Vehicle",
                    ),
                    (21, "Other"),
                    (92, "Contributing Circumstance - No Details"),
                    (98, "Not Reported"),
                    (99, "Reported as Unknown"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="parkedvehiclerelatedfactor",
            name="parked_vehicle_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (29, "Default Code Used for Vehicle Numbering"),
                    (30, "Multi-Wheeled Motorcycle Conversion"),
                    (32, "Vehicle Registration for a Person with a Disability"),
                    (33, "Vehicle Being Pushed by Non-Motorist"),
                    (35, "Reconstructed/Altered Vehicle"),
                    (36, "Electric/Alternative Fuel Vehicle (Since 1999)"),
                    (37, "Transporting Children to/From Head Start/Day Care"),
                    (
                        39,
                        "Highway Construction, Maintenance or Utility Vehicle, In-Transport (Inside or Outside Work Zone)",
                    ),
                    (40, "Highway Incident Response Vehicle(Since 2002)"),
                    (
                        41,
                        "Police Fire or EMS Vehicle Working at the Scene of an Emergency or Performing Other Traffic Control Activities",
                    ),
                    (
                        42,
                        "Other Working Vehicle (Not Construction, Maintenance, Utility, Police, Fire, or EMS Vehicle)",
                    ),
                    (44, "Adaptive Equipment"),
                    (45, "Slide-in Camper"),
                    (999, "Reported as Unknown"),
                ],
                default=0,
            ),
        ),
    ]
