# Generated by Django 4.2.16 on 2025-06-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fatalities",
            "0041_alter_nonmotoristcontributingcircumstance_nonmotorist_contributing_circumstance_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkedvehicle",
            name="emergency_vehicle_use",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Applicable"),
                    (1, "Yes"),
                    (2, "Non-Emergency, Non-Transport"),
                    (3, "Non-Emergency Transport"),
                    (4, "Emergency Operation, Emergency Warning Equipment Not in Use"),
                    (5, "Emergency Operation, Emergency Warning Equipment in Use"),
                    (
                        6,
                        "Emergency Operation, Emergency Warning Equipment in Use Unknown",
                    ),
                    (8, "Not Reported"),
                    (9, "Reported as Unknown"),
                ],
                default=8,
            ),
        ),
    ]
