# Generated by Django 4.2.16 on 2025-06-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0045_alter_accident_first_harmful_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkedvehiclerelatedfactor",
            name="parked_vehicle_related_factor",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None Noted"),
                    (29, "Default Code Used for Vehicle Numbering"),
                    (30, "Multi-Wheeled Motorcycle Conversion"),
                    (31, "Hit-and-Run Vehicle (1982-2008)"),
                    (32, "Vehicle Registration for a Person with a Disability"),
                    (33, "Vehicle Being Pushed by Non-Motorist"),
                    (35, "Reconstructed/Altered Vehicle"),
                    (36, "Electric/Alternative Fuel Vehicle (Since 1999)"),
                    (37, "Transporting Children to/From Head Start/Day Care"),
                    (
                        39,
                        "Highway Construction, Maintenance or Utility Vehicle, In-Transport (Inside or Outside Work Zone)",
                    ),
                    (40, "Highway Incident Response Vehicle(Since 2002)"),
                    (
                        41,
                        "Police Fire or EMS Vehicle Working at the Scene of an Emergency or Performing Other Traffic Control Activities",
                    ),
                    (
                        42,
                        "Other Working Vehicle (Not Construction, Maintenance, Utility, Police, Fire, or EMS Vehicle)",
                    ),
                    (44, "Adaptive Equipment"),
                    (45, "Slide-in Camper"),
                    (999, "Reported as Unknown"),
                ],
                default=0,
            ),
        ),
    ]
