# Generated by Django 4.2.16 on 2025-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0047_alter_driverrelatedfactor_driver_related_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="crash_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Impact"),
                    (
                        1,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Drive off Road",
                    ),
                    (
                        2,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Control/Traction Loss",
                    ),
                    (
                        3,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Avoid Collision With Vehicle, Pedestrian, Animal",
                    ),
                    (
                        4,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Specifics Other",
                    ),
                    (
                        5,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION A: RIGHT ROADSIDE DEPARTURE - Specifics Unknown",
                    ),
                    (
                        6,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Drive off Road",
                    ),
                    (
                        7,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Control/Traction Loss",
                    ),
                    (
                        8,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Avoid Collision With Vehicle, Pedestrian, Animal",
                    ),
                    (
                        9,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Specifics Other",
                    ),
                    (
                        10,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION B: LEFT ROADSIDE DEPARTURE - Specifics Unknown",
                    ),
                    (
                        11,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Parked Vehicle",
                    ),
                    (
                        12,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Stationary Object",
                    ),
                    (
                        13,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Pedestrian/Animal",
                    ),
                    (
                        14,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - End Departure",
                    ),
                    (
                        15,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        16,
                        "CATEGORY I: SINGLE DRIVER - CONFIGURATION C: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        20,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped",
                    ),
                    (
                        21,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Straight",
                    ),
                    (
                        22,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Left",
                    ),
                    (
                        23,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Stopped, Right",
                    ),
                    (
                        24,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower",
                    ),
                    (
                        25,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Straight",
                    ),
                    (
                        26,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Left",
                    ),
                    (
                        27,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Slower, Going Right",
                    ),
                    (
                        28,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing)",
                    ),
                    (
                        29,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Straight",
                    ),
                    (
                        30,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Left",
                    ),
                    (
                        31,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Decelerating (Slowing), Going Right",
                    ),
                    (
                        32,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Specifics Other",
                    ),
                    (
                        33,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION D: REAR END - Specifics Unknown",
                    ),
                    (
                        34,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        35,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        36,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        37,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        38,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        39,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        40,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        41,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        42,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        43,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION E: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        44,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Straight Ahead on Left",
                    ),
                    (
                        45,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Straight Ahead on Left/Right",
                    ),
                    (
                        46,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Changing Lanes to the Right",
                    ),
                    (
                        47,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Changing Lanes to the Left",
                    ),
                    (
                        48,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Specifics Other",
                    ),
                    (
                        49,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - CONFIGURATION F: SIDESWIPE/ANGLE - Specifics Unknown",
                    ),
                    (
                        52,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION G: HEAD-ON - Specifics Other",
                    ),
                    (
                        53,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION G: HEAD-ON - Specifics Unknown",
                    ),
                    (
                        54,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        55,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        56,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        57,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Control/Traction Loss, Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        58,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        59,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Contact Vehicle- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        60,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle’s Frontal Area Impacts Another Vehicle",
                    ),
                    (
                        61,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Avoiding Non-Fixed Object- Vehicle Is Impacted by Frontal Area of Another Vehicle",
                    ),
                    (
                        62,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Specifics Other",
                    ),
                    (
                        63,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION H: FORWARD IMPACT - Specifics Unknown",
                    ),
                    (
                        64,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Lateral Move (Left/Right)",
                    ),
                    (
                        65,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Lateral Move (Going Straight)",
                    ),
                    (
                        66,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Specifics Other",
                    ),
                    (
                        67,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - CONFIGURATION I: SIDESWIPE/ANGLE - Specifics Unknown",
                    ),
                    (
                        74,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION J: TURN ACROSS PATH - Specifics Other",
                    ),
                    (
                        75,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION J: TURN ACROSS PATH - Specifics Unknown",
                    ),
                    (
                        84,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION K: TURN INTO PATH - Specifics Other",
                    ),
                    (
                        85,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - CONFIGURATION K: TURN INTO PATH - Specifics Unknown",
                    ),
                    (
                        90,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - CONFIGURATION L: STRAIGHT PATHS - Specifics Other",
                    ),
                    (
                        91,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - CONFIGURATION L: STRAIGHT PATHS - Specifics Unknown",
                    ),
                    (101, "CATEGORY I: SINGLE DRIVER - Right Roadside Departure"),
                    (102, "CATEGORY I: SINGLE DRIVER - Left Roadside Departure"),
                    (
                        103,
                        "CATEGORY I: SINGLE DRIVER - Struck Object While Moving Forward",
                    ),
                    (
                        201,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Leading Vehicle",
                    ),
                    (
                        202,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Trailing Vehicle",
                    ),
                    (
                        203,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Rear End, Other or Unknown",
                    ),
                    (
                        204,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Frontal Impact After Maneuver",
                    ),
                    (
                        205,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Rear End Impact After Maneuver",
                    ),
                    (
                        206,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Forward Impact, Other or Unknown",
                    ),
                    (
                        207,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Sideswipe Angle, Vehicle on Left",
                    ),
                    (
                        208,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - Sideswipe Angle, Vehicle on Right",
                    ),
                    (
                        209,
                        "CATEGORY II: SAME TRAFFICWAY, SAME DIRECTION - (Sideswipe Angle, Other or Unknown",
                    ),
                    (
                        301,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move [Left/Right], Head-On, Sideswipe, or Angle",
                    ),
                    (
                        302,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move [Going Straight], Head-On, Sideswipe, or Angle",
                    ),
                    (
                        303,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Lateral Move, Other or Unknown",
                    ),
                    (
                        304,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Departed Lane",
                    ),
                    (
                        305,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Remained in Lane",
                    ),
                    (
                        306,
                        "CATEGORY III: SAME TRAFFICWAY, OPPOSITE DIRECTION - Frontal Impact After Maneuver, Other or Unknown",
                    ),
                    (
                        401,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Opposite Directions [Left/Right]",
                    ),
                    (
                        402,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Opposite Directions [Going Straight]",
                    ),
                    (
                        403,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Turning Right]",
                    ),
                    (
                        404,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Going Straight]",
                    ),
                    (
                        405,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Turning Left]",
                    ),
                    (
                        406,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Initial Same Directions [Going Straight]",
                    ),
                    (
                        407,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Across Path, Other or Unknown",
                    ),
                    (
                        408,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Turning Left]",
                    ),
                    (
                        409,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Going Straight]",
                    ),
                    (
                        410,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Turning Right]",
                    ),
                    (
                        411,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Same Direction [Going Straight]",
                    ),
                    (
                        412,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Turning Right]",
                    ),
                    (
                        413,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Going Straight]",
                    ),
                    (
                        414,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Turning Left]",
                    ),
                    (
                        415,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Turn into Opposite Directions [Going Straight]",
                    ),
                    (
                        416,
                        "CATEGORY IV: CHANGING TRAFFICWAY, VEHICLE TURNING - Turn Into Path, Other or Unknown",
                    ),
                    (
                        501,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Striking from the Right",
                    ),
                    (
                        502,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Struck on the Right",
                    ),
                    (
                        503,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Striking from the Left",
                    ),
                    (
                        504,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Struck on the Left",
                    ),
                    (
                        505,
                        "CATEGORY V: INTERSECTING PATHS (VEHICLE DAMAGE) - Straight Paths, Other or Unknown",
                    ),
                    (992, "CATEGORY VI: MISCELLANEOUS - Backing Vehicle"),
                    (993, "CATEGORY VI: MISCELLANEOUS - Other Vehicle"),
                    (998, "CATEGORY VI: MISCELLANEOUS - Other Crash Type"),
                    (999, "CATEGORY VI: MISCELLANEOUS - Unknown Crash Type"),
                ],
                default=999,
            ),
        ),
    ]
