# Generated by Django 4.2.16 on 2025-08-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0048_alter_vehicle_crash_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="lag_hours",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
