# Generated by Django 4.2.16 on 2025-09-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0049_alter_person_lag_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="moving_violation",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Manslaughter or Homicide"),
                    (
                        2,
                        "Willful Reckless Driving; Driving to Endanger; Negligent Driving",
                    ),
                    (3, "Unsafe Reckless (Not Willful, Wanton Reckless) Driving"),
                    (
                        4,
                        "Inattentive, Careless, Improper Driving, Driving Without Due Care",
                    ),
                    (5, "Fleeing or Eluding Police"),
                    (
                        6,
                        "Fail to Obey Police, Fireman, Authorized Person Directing Traffic",
                    ),
                    (7, "Hit-And-Run, Fail to Stop After Crash"),
                    (8, "Fail to Give Aid, Information, Wait for Police After Crash"),
                    (9, "Serious Violation Resulting in Death"),
                    (10, "Use of Telecommunications Device (Since 2015)"),
                    (
                        11,
                        "Driving While Intoxicated (Alcohol or Drugs) or BAC Above Limit (Any Detectable BAC for CDLs)",
                    ),
                    (12, "Driving While Impaired"),
                    (
                        13,
                        "Driving Under Influence of Substance Not Intended to Intoxicate",
                    ),
                    (14, "Drinking While Operating"),
                    (15, "Illegal Possession of Alcohol or Drugs"),
                    (16, "Driving With Detectable Alcohol"),
                    (18, "Refusal to Submit to Chemical Test"),
                    (19, "Alcohol, Drug or Impairment Violations Generally"),
                    (21, "Racing"),
                    (22, "Speeding (Above the Speed Limit)"),
                    (
                        23,
                        "Speed Greater Than Reasonable and Prudent (Not Necessarily Over the Limit)",
                    ),
                    (
                        24,
                        "Exceeding Special Speed Limit (for Trucks, Buses, Cycles, or on Bridge, in School Zone, etc.)",
                    ),
                    (25, "Energy Speed (Exceeding 55 mph, Non-Pointable)"),
                    (26, "Driving Too Slowly"),
                    (29, "Speed-Related Violations Generally"),
                    (31, "Fail to Stop for Red Signal"),
                    (32, "Fail to Stop for Flashing Red"),
                    (
                        33,
                        "Violation of Turn on Red (Fail to Stop and Yield, Yield to Pedestrians Before Turning)",
                    ),
                    (34, "Fail to Obey Flashing Signal (Yellow or Red)"),
                    (35, "Fail to Obey Signal Generally"),
                    (36, "Violate RR Grade Crossing Device/Regulations"),
                    (37, "Fail to Obey Stop Sign"),
                    (38, "Fail to Obey Yield Sign"),
                    (39, "Fail to Obey Traffic Control Device Generally"),
                    (
                        41,
                        "Turn in Violation of Traffic Control (Disobey Signs, Turn Arrow or Pavement Markings; This Is Not a Right-on-Red violation)",
                    ),
                    (42, "Improper Method and Position of Turn (Too Wide, Wrong Lane)"),
                    (43, "Fail to Signal for Turn or Stop"),
                    (45, "Fail to Yield to Emergency Vehicle"),
                    (46, "Fail to Yield Generally"),
                    (48, "Enter Intersection When Space Insufficient"),
                    (49, "Turn, Yield, Signaling Violations Generally"),
                    (51, "Driving Wrong Way on One-Way Road"),
                    (52, "Driving on Left, Wrong Side of Road Generally"),
                    (53, "Improper, Unsafe Passing"),
                    (54, "Pass on Right (Drive off Pavement to Pass)"),
                    (55, "Pass Stopped School Bus"),
                    (56, "Fail to Give Way When Overtaken"),
                    (58, "Following Too Closely"),
                    (59, "Wrong Side, Passing, Following Violations Generally"),
                    (61, "Unsafe or Prohibited Lane Change"),
                    (
                        62,
                        "Improper Use of Lane (Enter of 3-Lane Road, HOV Designated Lane)",
                    ),
                    (
                        63,
                        "Certain Traffic to Use Right Lane (Trucks, Slow Moving, etc.)",
                    ),
                    (
                        66,
                        "Motorcycle Lane Violations (More Than Two per Lane, Riding Between Lanes, etc.)",
                    ),
                    (67, "Motorcyclist Attached to Another Vehicle"),
                    (69, "Lane Violations Generally"),
                    (71, "Driving While License Withdrawn (Since 2014)"),
                    (72, "Other Driver License Violations"),
                    (
                        73,
                        "Commercial Driver Violations (Log Book, Hours, Permits Carried)",
                    ),
                    (74, "Vehicle Registration Violations"),
                    (75, "Fail to Carry Insurance Card"),
                    (76, "Driving Uninsured Vehicle"),
                    (79, "Non-Moving Violations Generally"),
                    (81, "Lamp Violations"),
                    (82, "Brake Violations"),
                    (83, "Failure to Require Restraint Use (by Self or Passenger)"),
                    (84, "Motorcycle Equipment Violations (Helmet, Special Equipment)"),
                    (85, "Violation of Hazardous Cargo Regulations"),
                    (86, "Size, Weight, Load Violations"),
                    (89, "Equipment Violations Generally"),
                    (91, "Parking"),
                    (92, "Theft, Unauthorized Use of Motor Vehicle"),
                    (
                        93,
                        "Driving Where Prohibited (Sidewalk, Limited Access, off Truck Route)",
                    ),
                    (95, "No Driver Present/Unknown if Driver Present"),
                    (97, "Not Reported"),
                    (98, "Other Moving Violation"),
                    (99, "Unknown Violations"),
                    (101, "Yes"),
                    (102, "Pending"),
                ],
                default=0,
            ),
        ),
    ]
