# Generated by Django 4.2.16 on 2025-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0050_alter_violation_moving_violation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="functional_system",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Interstate"),
                    (2, "Other Freeways and Expressways"),
                    (3, "Other Principal Arterial"),
                    (4, "Minor Arterial"),
                    (5, "Major Collector"),
                    (6, "Minor Collector"),
                    (7, "Local"),
                    (96, "Trafficway Not In State Inventory"),
                    (98, "Not Reported"),
                    (99, "Unknown"),
                ],
                default=99,
            ),
        ),
    ]
