# Generated by Django 4.2.16 on 2025-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0051_alter_accident_functional_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="dot_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="population_description",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
