# Generated by Django 4.2.16 on 2025-10-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0052_state_dot_name_state_population_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(blank=True, null=True)),
                ("log", models.TextField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fatalities.podcastepisode",
                    ),
                ),
            ],
        ),
    ]
