# Generated by Django 4.2.16 on 2025-10-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0053_podcastdownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="InjuryAccident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state_accident_id", models.IntegerField()),
                ("dt", models.DateTimeField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("city", models.TextField(blank=True, null=True)),
                ("county", models.TextField(blank=True, null=True)),
                ("street_1", models.TextField(null=True)),
                ("street_2", models.TextField(null=True)),
                ("crash_type", models.TextField(blank=True, null=True)),
                (
                    "death_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "severe_injury_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fatalities.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InjuryVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.PositiveSmallIntegerField()),
                ("make", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("body_type", models.TextField(blank=True, null=True)),
                ("violation", models.TextField(blank=True, null=True)),
                ("hit_and_run", models.BooleanField(default=False)),
                (
                    "injury_accident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fatalities.injuryaccident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InjuryPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_person_id", models.IntegerField(blank=True, null=True)),
                ("age", models.PositiveSmallIntegerField(null=True)),
                (
                    "sex",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Male"),
                            (2, "Female"),
                            (3, "Other"),
                            (8, "Not Reported"),
                            (9, "Reported as Unknown"),
                        ],
                        default=8,
                    ),
                ),
                (
                    "person_type",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "injury_severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Apparent Injury (O)"),
                            (1, "Possible Injury (C)"),
                            (2, "Suspected Minor Injury (B)"),
                            (3, "Suspected Serious Injury (A)"),
                            (4, "Fatal Injury (K)"),
                            (5, "Injured, Severity Unknown (U) (Since 1978)"),
                            (6, "Died Prior to Crash"),
                            (9, "Unknown/Not Reported"),
                        ],
                        default=9,
                    ),
                ),
                (
                    "injury_accident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fatalities.injuryaccident",
                    ),
                ),
                (
                    "injury_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fatalities.injuryvehicle",
                    ),
                ),
            ],
        ),
    ]
