# Generated by Django 4.2.16 on 2025-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0054_injuryaccident_injuryvehicle_injuryperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuryperson",
            name="sex",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
