# Generated by Django 4.2.16 on 2025-10-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0055_alter_injuryperson_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="injuryperson",
            name="state_person_id",
        ),
    ]
