# Generated by Django 4.2.16 on 2025-10-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0056_remove_injuryperson_state_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuryaccident",
            name="state_accident_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="injuryperson",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
