# Generated by Django 4.2.16 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatalities", "0057_alter_injuryaccident_state_accident_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuryaccident",
            name="state_accident_id",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
