# Generated by Django 4.2.29 on 2026-04-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatalities', '0058_alter_injuryaccident_state_accident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryaccident',
            name='crash_severity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='injuryaccident',
            name='motorcycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injuryaccident',
            name='number_of_nonmotorists',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injuryaccident',
            name='number_of_vehicles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
