# Generated by Django 4.2.29 on 2026-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatalities', '0060_alter_driverrelatedfactor_driver_related_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryaccident',
            name='state_accident_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
