# Generated by Django 4.2.29 on 2026-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatalities', '0061_alter_injuryaccident_state_accident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='route_signing',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Signed'), (1, 'Interstate'), (2, 'U.S. Highway'), (3, 'State Highway'), (4, 'County'), (5, 'Township'), (6, 'Municipal'), (7, 'Local Street - Frontage Road'), (8, 'Other'), (10, 'Parkway Marker or Forest Route Marker'), (11, 'Off-Interstate Business Marker'), (12, 'Secondary Route'), (13, 'Bureau of Indian Affairs'), (95, 'Other'), (96, 'Trafficway Not in State Inventory'), (99, 'Unknown/Not Reported')], default=99),
        ),
    ]
