"""
Django settings for data project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT=os.environ.get("MEDIA_ROOT", "podcasts")
MEDIA_URL=os.environ.get("MEDIA_URL", "podcasts/")
STATIC_ROOT=os.environ.get("STATIC_ROOT", "/var/www/static")
STATICFILES_DIRS = [
    "/home/tonydeals/app/ntsb/data/fatalities/templates/static",
    "/root/ntsb/data/fatalities/templates/static"
#     "/var/www/static/",
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$@0+!h+srs+u_q&2k98050j!8=ym=w(%^+b+6(&c1z=ui(6)94"

GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "You Wish!")

GEOIP_PATH = os.environ.get("GEOIP_PATH", "/home/tonydeals/geo")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (bool(int(os.environ.get('DEBUG',1))))

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "127.0.0.1:8000", "roadway.report", "www.roadway.report", "45.33.29.42"]

CSV_PATH = os.environ.get("CSV_PATH", "/home/tonydeals/app/ntsb/data/csvs/")

ACCIDENT_CSV_PATHS = {
    1975: '1975/ACCIDENT.CSV',
    1976: '1976/ACCIDENT.CSV',
    1977: '1977/ACCIDENT.CSV',
    1978: '1978/ACCIDENT.CSV',
    1979: '1979/ACCIDENT.CSV',
    1980: '1980/ACCIDENT.CSV',
    1981: '1981/ACCIDENT.CSV',
    1982: '1982/ACCIDENT.CSV',
    1983: '1983/ACCIDENT.CSV',
    1984: '1984/ACCIDENT.CSV',
    1985: '1985/ACCIDENT.CSV',
    1986: '1986/ACCIDENT.CSV',
    1987: '1987/ACCIDENT.CSV',
    1988: '1988/ACCIDENT.CSV',
    1989: '1989/ACCIDENT.CSV',
    1990: '1990/ACCIDENT.CSV',
    1991: '1991/ACCIDENT.CSV',
    1992: '1992/ACCIDENT.CSV',
    1993: '1993/ACCIDENT.CSV',
    1994: '1994/ACCIDENT.CSV',
    1995: '1995/ACCIDENT.CSV',
    1996: '1996/ACCIDENT.CSV',
    1997: '1997/ACCIDENT.CSV',
    1998: '1998/ACCIDENT.CSV',
    1999: '1999/ACCIDENT.CSV',
    2000: '2000/ACCIDENT.CSV',
    2001: '2001/ACCIDENT.CSV',
    2002: '2002/ACCIDENT.CSV',
    2003: '2003/ACCIDENT.CSV',
    2004: '2004/ACCIDENT.CSV',
    2005: '2005/ACCIDENT.CSV',
    2006: '2006/FARS2006NationalCSV/ACCIDENT.CSV',
    2007: '2007/FARS2007NationalCSV/ACCIDENT.CSV',
    2008: '2008/FARS2008NationalCSV/ACCIDENT.CSV',
    2009: '2009/FARS2009NationalCSV/ACCIDENT.CSV',
    2010: '2010/FARS2010NationalCSV/ACCIDENT.CSV',
    2011: '2011/FARS2011NationalCSV/ACCIDENT.CSV',
    2012: '2012/FARS2012NationalCSV/ACCIDENT.csv',
    2013: '2013/FARS2013NationalCSV/ACCIDENT.csv',
    2014: '2014/FARS2014NationalCSV/ACCIDENT.csv',
    2015: '2015/FARS2015NationalCSV/accident.csv',
    2016: '2016/accident.CSV',
    2017: '2017/accident.CSV',
    2018: '2018/accident.csv',
    2019: '2019/FARS2019NationalCSV/accident.CSV',
    2020: '2020/FARS2020NationalCSV/accident.csv',
    2021: '2021/FARS2021NationalCSV/accident.csv',
    2022: '2022/FARS2022NationalCSV/accident.csv',
    2023: '2023/FARS2023NationalCSV/accident.csv'
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fatalities",
    "django_extensions"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "data.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "data.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "HOST": "localhost",
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "crash",
        "USER": "app",
        "PASSWORD": "assword",
    },
}


SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    }
}

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "ERROR",
#             "class": "logging.FileHandler",
#             "filename": "/var/log/django_errors.log",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file"],
#             "level": "ERROR",
#             "propagate": True,
#         },
#     },
# }

MASTODON_FIRST_SECRET = os.environ.get("MASTODON_FIRST_SECRET", "")
MASTODON_LOGIN_PASSWORD = os.environ.get("MASTODON_LOGIN_PASSWORD", "")
MASTODON_SECOND_SECRET = os.environ.get("MASTODON_SECOND_SECRET", "")

REDDIT_CLIENT_ID = os.environ.get("REDDIT_CLIENT_ID", "")
REDDIT_CLIENT_SECRET = os.environ.get("REDDIT_CLIENT_SECRET", "")

REDDIT_REFRESH_TOKEN = os.environ.get("REDDIT_REFRESH_TOKEN", "")

TILES_URL = os.environ.get("TILES_URL", "pmtiles://http://127.0.0.1:8080/")
TEMPLATES_PATH = os.environ.get("TEMPLATES_PATH", "fatalities/templates/")